## PanglaoDB, CollecTRI

In [1]:
import decoupler as dc

In [2]:
dc.__version__

# v '2.1.1'

'2.1.1'

In [3]:
collectri = dc.op.collectri(organism="human") #downloaded on 19/05/2026
panglaodb = dc.op.resource("PanglaoDB", organism="human") #downloaded on 19/05/2026

In [4]:
panglaodb

,genesymbol,canonical_marker,cell_type,germ_layer,human,human_sensitivity,human_specificity,mouse,mouse_sensitivity,mouse_specificity,ncbi_tax_id,organ,ubiquitiousness
,,,,,,,,,,,,,
0,A1CF,False,Hepatocytes,Endoderm,True,0.189189,0.004437,True,0.175000,0.000257,9606,Liver,0.002
1,A2APA5,False,Germ cells,Mesoderm,False,0.000000,0.000000,True,0.432927,0.000000,10090,Reproductive,0.004
2,A2M,True,Bergmann glia,Ectoderm,True,0.000000,0.062343,True,0.333333,0.001604,9606,Brain,0.012
3,A3FIN4,False,Mast cells,Mesoderm,False,0.000000,0.000000,True,0.184211,0.000708,10090,Immune system,0.001
4,A4GALT,True,Mast cells,Mesoderm,True,0.000000,0.014133,True,0.000000,0.003023,9606,Immune system,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8206,ZNF521,False,Adipocyte progenitor cells,Mesoderm,True,0.000000,0.010338,False,0.000000,0.000000,9606,Connective tissue,0.002
8207,ZNRF4,False,Germ cells,Mesoderm,True,0.284360,0.000000,True,0.000000,0.000000,9606,Reproductive,0.010
8208,ZPBP2,True,Germ cells,Mesoderm,True,0.436019,0.000000,True,0.000000,0.000000,9606,Reproductive,0.008
8209,ZRSR2P1,False,Neurons,Ectoderm,True,0.000000,0.000000,True,0.000000,0.000000,9606,Brain,0.005
8210,ZSCAN10,False,Embryonic stem cells,Epiblast,True,0.000000,0.000313,True,0.000000,0.000000,9606,Zygote,0.000

In [34]:
collectri.to_csv('../../../data/decoupler/collectri.csv')
panglaodb.to_csv('../../../data/decoupler/panglaodb.csv')

In [12]:
import pandas as pd
from ast import literal_eval
df = pd.read_csv('/home/lnemati/fardin/intact_direct.csv')
assert type(df['all_genes'].apply(literal_eval).iloc[0]) == list
print('All good!')

All good!

## Celltype Fractions

In [48]:
import pandas as pd
import glob
import os

ct_cols = [
    'Lymphocytes',
    'Neutrophils',
    'Eosinophils',
    'Mast_Cells',
    'Dendritic_Cells',
    'Macrophages',
    'tumor_purity',
]

other_cols = [
    'condition',
    'tissue'
]

tissue_dir = '/home/lnemati/pathway_crosstalk/data/survival_data/tissues'

# All columns to keep
use_cols = ct_cols + other_cols

# Find all CSV files
csv_files = glob.glob(os.path.join(tissue_dir, '*.csv'))

dfs = []
for file in csv_files:
    print(file)
    if file == '/home/lnemati/pathway_crosstalk/data/survival_data/tissues/pan_cancer.csv':
        continue
        
    df = pd.read_csv(
        file,
        usecols=lambda col: col in use_cols or col == 'Unnamed: 0',
        index_col=0
    )
    dfs.append(df)

# Concatenate all dataframes
final_df = pd.concat(dfs)

# Optional: reset index name if needed
# final_df.index.name = None

print(final_df.shape)

/home/lnemati/pathway_crosstalk/data/survival_data/tissues/lung.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/bladder.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/thymus.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/pan_cancer.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/prostate.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/liver.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/uterus.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/rectum.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/brain.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/testis.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/adrenal_gland.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/kidney.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/head_and_neck_region.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/lymphatic_tissue.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/paraganglia.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/esophagus.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/stomach.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/white_blood_cell.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/bile_duct.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/soft_tissue_bone.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/colon.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/eye.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/thyroid.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/endometrium.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/lining_of_body_cavities.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/cervix.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/ovary.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/breast.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/pancreas.csv
/home/lnemati/pathway_crosstalk/data/survival_data/tissues/skin.csv
(10491, 9)

In [49]:
final_df

,condition,tissue,Lymphocytes,Neutrophils,Eosinophils,Mast_Cells,Dendritic_Cells,Macrophages,tumor_purity
TCGA-05-4244-01,Lung Adenocarcinoma,Lung,0.319964,0.000000,0.0,0.037055,0.054944,0.588037,0.44
TCGA-05-4250-01,Lung Adenocarcinoma,Lung,NaN,NaN,NaN,NaN,NaN,NaN,0.50
TCGA-05-4382-01,Lung Adenocarcinoma,Lung,0.336943,0.000000,0.0,0.043183,0.003205,0.616669,0.21
TCGA-05-4384-01,Lung Adenocarcinoma,Lung,0.443620,0.016567,0.0,0.030681,0.003356,0.505775,0.49
TCGA-05-4389-01,Lung Adenocarcinoma,Lung,0.475052,0.006767,0.0,0.119110,0.067985,0.331086,0.48
...,...,...,...,...,...,...,...,...,...
TCGA-YG-AA3O-06,Skin Cutaneous Melanoma,Skin,0.510594,0.000000,0.0,0.016321,0.004864,0.468221,0.62
TCGA-YG-AA3P-06,Skin Cutaneous Melanoma,Skin,0.473950,0.000000,0.0,0.007200,0.000000,0.518850,0.97
TCGA-Z2-A8RT-06,Skin Cutaneous Melanoma,Skin,0.610817,0.000000,0.0,0.010945,0.013561,0.364677,0.83
TCGA-Z2-AA3S-06,Skin Cutaneous Melanoma,Skin,0.541362,0.000000,0.0,0.000000,0.000000,0.458638,0.91
TCGA-Z2-AA3V-06,Skin Cutaneous Melanoma,Skin,0.498248,0.000000,0.0,0.028135,0.000000,0.473616,0.45

In [50]:
#final_df.to_csv('/home/lnemati/pathway_crosstalk/data/survival_data/celltype_fractions.csv')

In [57]:

import pandas as pd
import glob
import os
from concurrent.futures import ProcessPoolExecutor

parent_dir = '/projects/bioinformatics/DB/Xena/TCGA_GTEX/by_tissue_primary_vs_normal'

use_cols = [
    'ligand',
    'receptor',
    'interaction',
    'all_genes',
    'corr'
]

# Use iglob (memory efficient)
csv_iter = glob.iglob(
    os.path.join(parent_dir, '**', 'interactions', 'ccc_lr_pairs.csv'),
    recursive=True
)

def load_file(f):
    parts = f.split(os.sep)
    
    tissue = parts[-5]
    condition = parts[-4]
    cancer_type = parts[-3]
    
    # Try fast engine if available
    try:
        df = pd.read_csv(f, usecols=use_cols, engine="pyarrow")
    except Exception:
        df = pd.read_csv(f, usecols=use_cols)
    
    df['tissue'] = tissue
    df['condition'] = condition
    df['cancer_type'] = cancer_type
    
    return df

# Parallel load
with ProcessPoolExecutor() as executor:
    dfs = list(executor.map(load_file, csv_iter))

# Combine
final_df = pd.concat(dfs, ignore_index=True)

print(f"Loaded {len(dfs)} files, shape: {final_df.shape}")

Loaded 78 files, shape: (292344, 8)

In [59]:
final_df.to_csv('/home/lnemati/pathway_crosstalk/results/corr_interactions/corr_ccc_lr_pairs.csv')

In [55]:
os.path.join(parent_dir, '**', '*interactions', 'ccc_lr_pairs.csv')

'/projects/bioinformatics/DB/Xena/TCGA_GTEX/by_tissue_primary_vs_normal/**/*interactions/ccc_lr_pairs.csv'

ERROR! Session/line number was not unique in database. History logging moved to new session 6724